version: '3.7'

services:
  dabase:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=senha
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: rentx
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
